# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.6"
  - "3.5"
  - "3.4"
  - "3.3"
  - "2.7"
  - "2.6"
  - "pypy"

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
    - pip install -r requirements.txt
    - pip install flake8

before_script:
    flake8 . --count --ignore=E402 --max-line-length=127 --statistics --exit-zero

# command to run tests, e.g. python setup.py test
script: python setup.py test

notifications:
    on_success: change
    on_failure: always
