dist: xenial
language: python
matrix:
  include:
    - python: 2.7
      name: "Test Python 2.7"
      env: TOXENV=py27
      install: pip install tox
      script: tox
    - python: 3.6
      name: "Test Python 3.6"
      env: TOXENV=py36
      install: pip install tox
      before_install:
        # Install neccessary Linux dependencies to build wxPython.
        #   See: https://github.com/wxWidgets/Phoenix/blob/master/.azure/ci-linux-job.yml
        - sudo apt-get update
        - sudo apt-get install -y build-essential python3-dev libgtk-3-dev libjpeg-dev libtiff-dev
      script:
        # Pass -vvv to pip through tox because wxPython can take ~20min to build and
        # Travis CI thinks that the build has stalled unless build progress is output.
        - tox -vvvvv
    - python: 3.7
      name: "Test Python 3.7"
      env: TOXENV=py37
      install: pip install tox
      script: tox
    - python: 3.6
      name: "Check formatting"
      install: pip install black isort
      script:
        - black --check --diff skidl tests setup.py
        - isort --check --diff --recursive tests skidl setup.py
